### ISSUE TITLE
Either the magnet, or the magnetic force produced by the coil is too weak

### ISSUE THREAD

**Issue by zubenelacribi** [radostin-stefanov/push-up-magnetic-levitation#2]
I was trying to write some code that reacts to the Hall effect sensor by using its amplified signal. Then I switched to floating average using the last 20 to 300 readings. Then I included another sensor on the other side of the coil in order to cancel the noise I read from the first one when the coil is repeatedly turned on and off. The problem with the latter approach was the the signal should pass through an amplifier to achieve the same form and I'm not sure about the offset of the signal compared to the one coming from the first sensor. I could not compare the two signals because the Y channel of the oscilloscope is damaged and shows just noise. By comparing the signals sequentially using the X channel only, it seemed that they are identical.

There is a short range of the potentiometer where the amplified signal from the sensor becomes clear. Going outside this range puts the amplifier in saturation. When we are in this range, the coil becomes repeatedly switched on and off and it begins to attract the magnet. But the magnet either sticks to the coil (too strong attraction), or falls down (too weak attraction).

I could not achieve the appropriate settings to make the magnet hang and switched back to the code of the Chinese guy. The problems there were the same -- either too strong, or too weak attraction and no hardware or software settings could make the magnet hang. I switched to the coil with thinner wire, tried it with 12V and 24V, then switched back to the coil with thicker wire and tried both voltages. Nothing helped.

It seems that even if there is some range of distances from the coil were the magnet can hang, it's too thin to find it right away. I believe that it depends on the magnet's strength, so we should try with a stronger magnet. On the other hand, the H-bridge doesn't get hot even at 24V, which means that the current flowing through it is not very big and the magnetic force that the coil produces is not enough. The coil is unable to attract the magnet when it's 5mm away, but this was possible before, so the problem is in the settings.

So we should try to make our own coil (we should do some calculations first) and try with different magnets. We should carefully look at the picture provided by the oscilloscope in order to decide which settings to change. I believe we can apply two sensors (on the top and the bottom side of the coil) and floating average of their readings (flatting the spikes) to remove the noise coming from the coil when switching it on and off. Thus we'll receive the pure signal which corresponds to the magnet's distance from the coil and we'll be able to control the coil easily.

**Comment by radostin-stefanov** [comment]
We should make first coil winder with counter. Just some simple solution with one servo, or switch like this one http://www.instructables.com/id/Coil-winder-with-automatic-counter/?ALLSTEPS

**Comment by borisov-r** [comment]
My oppinion is that you shouldn't focus on this machine at this time. I suggest to create a simple manual coil winding machine as shown here: [https://www.youtube.com/watch?v=exTSshSfXP4]
I think that there should be such machine in the lab if I haven't taken it. Otherwise it is at home unfortunatelly.
Regarding the comments. You should be able to control the current by changing the frequency or the PWM. This will define the distance of the permanent magnet to the coil. I think the experiment is much better, because the simulations are really hard to set up (at least for 3D simulations using standard field simulators like meep, openEMS or other). I know one simulator which is 2D and is quite fast called Hermes (http://www.hpfem.org/). I could try to make some simulation with it, but still we will have some numbers for the field strenght, but if it works in reality only experiment can prove.

**Comment by zubenelacribi** [comment]
We made the machine and put a simple arduino counter, and made 2 coils -- one experimental with thin wire (heats up too fast) and another one with phi 1mm coil wire wound around a bolt (480 winds, 250g of wire overall). The latter coil is good enough for testing since it nearly doesn't heat up. So we now know what coil wire to use and the issue is resolved.
